variables:
  CYPRESS_CACHE_FOLDER: "/home/cypress/.cache"
  CYPRESS_INSTALL_BINARY: "0"

npm-install:
  image: node:14.15-alpine
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - rest-calculator-angular/.npm
  script:
    - cd rest-calculator-angular
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - rest-calculator-angular/node_modules

build-frontend:
  image: node:14.15-alpine
  stage: build
  script:
    - cd rest-calculator-angular
    - npm run build
  artifacts:
    paths:
      - rest-calculator-angular/dist/

test-frontend:
  image: localhost:32000/nodejs-cypress-chrome:latest
  stage: test
  script:
    - cd rest-calculator-angular
    - npm run test-ci

e2e-test-frontend:
  image: localhost:32000/nodejs-cypress-chrome:latest
  stage: test
  script:
    - cd rest-calculator-angular
    - npm run e2e
  artifacts:
    when: always
    paths:
      - rest-calculator-angular/cypress/videos/**/*.mp4
      - rest-calculator-angular/cypress/screenshots/**/*.png
    expire_in: 5 days

deploy-frontend:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ '' ]
  stage: deploy
  script:
    - kubectl config get-contexts
#    - kubectl config use-context firm2020/taschenrechner:k8s-firm2020-dadevops-dev
    - kubectl get pods
