build-frontend:
  image: node:16.15-alpine
  stage: build
  script:
    - cd rest-calculator-angular
    - npm ci --prefer-offline
    - node_modules/@angular/cli/bin/ng version

test-frontend:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test
  script:
    - cd rest-calculator-angular
    - node_modules/@angular/cli/bin/ng test --configuration=ci

e2e-test-frontend:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test
  script:
    - cd rest-calculator-angular
    - node_modules/@angular/cli/bin/ng e2e
