install_dependencies:
  image: node:16.15-alpine
  stage: build
  script:
    - cd rest-calculator-angular
    - npm install
  artifacts:
    paths:
      - node_modules/
     

build-frontend:
  image: node:16.15-alpine
  stage: build
  dependencies:
    - install_dependencies
  script:
    - cd rest-calculator-angular
    - node_modules\@angular\cli\bin\ng version

test-frontend:
  image: node:16.15-alpine
  stage: test
  script:
    - cd rest-calculator-angular
    - npm run test

e2e-test-frontend:
  image: node:16.15-alpine
  stage: test
  script:
    - cd rest-calculator-angular
    - npm run e2e
