cache:
  paths:
    - .m2/repository/
variables:
  SONAR_TOKEN: "your-sonarqube-token"
  SONAR_HOST_URL: "http://your-sonarqube-url"
  GIT_DEPTH: 0
build-backend:
  image: maven:3.8-openjdk
  stage: build
  script:
    - cd rest-calculator
    - mvn clean install
test-backend:
  image: maven:3.8-openjdk
  stage: test
  dependencies:
    - build-backend
  script:
    - cd rest-calculator
    - mvn test
deploy-backend:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context firm2020/taschenrechner:k8s-firm2020-dadevops-dev
    - kubectl get pods

