variables:
  SONAR_TOKEN: "your-sonarqube-token"
  SONAR_HOST_URL: "http://your-sonarqube-url"
  GIT_DEPTH: 0

build-backend:
  image: maven:3.8-openjdk
  stage: build
  script:
    - cd rest-calculator
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - rest-calculator/target/*.jar
    expire_in: 2 days

test-backend:
  image: maven:3.8-openjdk
  stage: test
  script:
    - cd rest-calculator
    - mvn test

deploy-backend:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ '' ]
  stage: deploy
  dependencies:
    - build-backend
  script:
    - kubectl config get-contexts
    - kubectl config use-context firm2020/taschenrechner:k8s-firm2020-dadevops-dev
    - kubectl get pods